#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : SDL2_net
Version  : 2.0.1
Release  : 12
URL      : https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz
Source0  : https://www.libsdl.org/projects/SDL_net/release/SDL2_net-2.0.1.tar.gz
Summary  : SDL portable network library
Group    : Development/Tools
License  : Zlib
Requires: SDL2_net-lib = %{version}-%{release}
Requires: SDL2_net-license = %{version}-%{release}
BuildRequires : SDL2-dev

%description
This is a portable network library for use with SDL.

%package dev
Summary: dev components for the SDL2_net package.
Group: Development
Requires: SDL2_net-lib = %{version}-%{release}
Provides: SDL2_net-devel = %{version}-%{release}

%description dev
dev components for the SDL2_net package.


%package lib
Summary: lib components for the SDL2_net package.
Group: Libraries
Requires: SDL2_net-license = %{version}-%{release}

%description lib
lib components for the SDL2_net package.


%package license
Summary: license components for the SDL2_net package.
Group: Default

%description license
license components for the SDL2_net package.


%prep
%setup -q -n SDL2_net-2.0.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541027859
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1541027859
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/SDL2_net
cp COPYING.txt %{buildroot}/usr/share/package-licenses/SDL2_net/COPYING.txt
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/SDL2/SDL_net.h
/usr/lib64/libSDL2_net.so
/usr/lib64/pkgconfig/SDL2_net.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2_net-2.0.so.0
/usr/lib64/libSDL2_net-2.0.so.0.0.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/SDL2_net/COPYING.txt
